### ISSUE TITLE
Issue with predefined station list (stations.json)

### ISSUE THREAD

**Issue by fl0x53** [FL550/simple_dwd_weatherforecast#14]
Hi,
I just came around to an issue with the `station.json` file when updating the HCAS dwd weather add-on to v2.0.

First, I just noticed that the somehow migrated station was displaying "wrong" data. I re-added, in my case the station of Nürnberg Airport, and noticed that the station IDs differ.

Second, in home assistant when you configure the add-on you will get a list of weather stations close by. There I noticed a vast of stations that are historic: The stations were once operated by the DWD, but have since been decommissioned (e.g. Station Tennenlohe `ID 11659` out of service since 24.04.1978 [1]).

Now comes the fun part: DWD somehow re-uses those IDs 🤦‍♂️. So the ID from my example (11659) now maps to Přibyslav in Czech Republic [2]. Hence, you select a station nearby and get data from else where 😄

So I guess the station file needs a little rework.

[1]: https://www.dwd.de/DE/leistungen/klimadatendeutschland/statliste/statlex_html.html?view=nasPublication&nn=16102.html
[2]: https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/mosmix_stationskatalog.cfg?view=nasPublication&nn=16102

**Comment by FL550** [comment]
Wow, thank you very much for pointing this out! I'll have a closer look on this.

**Comment by FL550** [comment]
I have updated the list in v2.0.14. Thanks for pointing this out!
