### ISSUE TITLE
Wrong geographic coordinates in stations.json

### ISSUE THREAD

**Issue by fl0x53** [FL550/simple_dwd_weatherforecast#18]
Due to an incorrect representation of the geographic coordinates in the source file for the MOSMIX stations [#1][1] their position is incorrect.
On [#1][1] the position is _not_ in decimal format, but in degree and minutes separated by a dot.

Example
```
ID    ICAO NAME                 LAT    LON     ELEV
10763 EDDN NUERNBERG             49.30   11.03   318
```

whereas [#2][2]:
```
Stations-Kennziffer | Stations_ID | ICAO-Kennung | Stationsname | Stationshöhe in Metern | geogr. Breite | geogr. Länge
10763 | 3668 | EDDN | Nürnberg | 314 | 49° 30' | 11° 03'
``` 
And [#3][3] states the exact decimal coordinates as 49.503, 11.0549

So for the time being, I would suggest parsing the incorrect values. Dividing the places after the decimal point by 60 to convert from arcminute to decimal.  With the values from the example resulting in `49.5, 11,05`. This should be sufficient to find the next station.

I only became aware of the error because the Home Assistan Integration suggested stations that are really not that close by! 😉 

[1]: https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/mosmix_stationskatalog.cfg?view=nasPublication
[2]: https://www.dwd.de/DE/leistungen/klimadatendeutschland/stationsuebersicht.html
[3]: https://cdc.dwd.de/rest//metadata/station/html/812300445479

**Comment by FL550** [comment]
Thanks for the heads up! This error was introduced when I changed the generation of the stations.json file. It's fixed now.
