### ISSUE TITLE
Latitude and Longitude from DWD are not decimal values

### ISSUE THREAD

**Issue by hanzoh** [FL550/simple_dwd_weatherforecast#2]
I was wondering why the home assistant integration was returning a station which is far away from the lat/long from my home.
I have then checked the values that DWD provides in their station list.
If they write 50.25 they don’t mean the decimal value 50.25, but 50 degrees, 25 minutes.
I‘m on my phone right now and can’t type the degree symbol, but you can check this in google maps when you type 50\*25'N 7\*13'E in the search bar (replace * with the degree symbol).

**Comment by FL550** [comment]
Oh thanks for the heads-up, I'll fix this!

**Comment by FL550** [comment]
This is fixed in the new version!
