### ISSUE TITLE
Debug code in dwdforecast.py?

### ISSUE THREAD

**Issue by armin-gh** [FL550/simple_dwd_weatherforecast#23]
Nothing serious, looks like during one of the latest you changes you left some debug code/print statements in dwdforecast.py, function "get_daily_condition"?

Found this in my log:
```
Sep 03 20:20:01 smarthome hass[22417]: testieng
Sep 03 20:20:01 smarthome hass[22417]: working

```

Armin

**Comment by FL550** [comment]
Ah, I forgot them, indeed. I'll implement new features today and will remove this as well. Thanks for reporting!
