### ISSUE TITLE
aktuelle Wettermesswerte

### ISSUE THREAD

**Issue by martin3000** [FL550/simple_dwd_weatherforecast#6]
https://opendata.dwd.de/weather/weather_reports/poi/

**Comment by FL550** [comment]
These values are not realtime values, but rather historical data.

**Comment by martin3000** [comment]
you are right, the values are already 10 minutes old

**Comment by FL550** [comment]
The values are only reported every hour and updated 40 minutes after the hour. Do you really want these values?

**Comment by martin3000** [comment]
I think I was posting this as a reaction to your post 
`Please note, that the "current" weather values are not measured values. The values shown are the forecasted values for the actual hour. The forecast itself is updated every 6 hours. If anyone knows a source for actual measurements, please let me know.`
(weather data for HA)
