### ISSUE TITLE
KML parsing error

### ISSUE THREAD

**Issue by SpiGAndromeda** [FL550/simple_dwd_weatherforecast#9]
Unfortuneatly, I found another problem and I am not sure how to fix it (I am actually a PHP developer).

The parsing of the KML file fails with an an "list index out of range" error.
```
File "/usr/local/lib/python3.9/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 469, in update
    self.parse_kml(kml)
File "/usr/local/lib/python3.9/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 496, in parse_kml
    result = tree.xpath("//dwd:IssueTime", namespaces=self.namespaces)[0].text
IndexError: list index out of range
```

The used station was 10677. I checked the file manually and it looks exactly like the others:
[MOSMIX_L_2022050815_10677.kml](https://github.com/FL550/simple_dwd_weatherforecast/files/8647532/MOSMIX_L_2022050815_10677.kml.txt) (renamed the file to .txt to allow upload on GitHub)

I guess the error is about this XML line:
```xml
<dwd:IssueTime>2022-05-08T15:00:00.000Z</dwd:IssueTime>
```

I also checked lxml and there were no recent updates that could explain this error.

These are my HA infos:
> Version | core-2022.5.2
> Installation Type | Home Assistant OS
> Development | false
> Supervisor | true
> Docker | true
> User | root
> Virtual Environment | false
> Python Version | 3.9.9
> Operating System Family | Linux
> Operating System Version | 5.10.103-v8
> CPU Architecture | aarch64
> Timezone | Europe/Berlin

Home Assistant Community Store:
> GitHub API | ok
> GitHub Content | ok
> GitHub Web | ok
> GitHub API Calls Remaining | 4855
> Installed Version | 1.24.5
> Stage | running
> Available Repositories | 1115
> Downloaded Repositories | 17

best regards,
spigandromeda

P.S. the error occurred only after I installed the HTTP patch (download results with HTTP and HTTPS are the same).

**Comment by GerdRuetten** [comment]
I have the same issue.

The problem is, that the SSL-Certificat from DWD is expired, so the https-URL are invalid

NET::ERR_CERT_DATE_INVALID
Subject: opendata.dwd.de
Issuer: DFN-Verein Global Issuing CA
Expires on: 08.05.2022
Current date: 09.05.2022

Don't switch to an unsafe http-URL because the DWD-Side use HSTS!

Wait for DWD to fix the error

**Comment by FL550** [comment]
Sorry for the inconvenience. But I forgot HSTS totally. I will undo the changes. So unfortunately we all have to wait.

**Comment by SpiGAndromeda** [comment]
@FL550 could you wait a bit until we ware sure about that?

@GerdRuetten are you sure about that? I collected the traffic outgoing from my HA installation and opened the dump with Wireshark. The HTTP response seems ok. Before I created the PR for switching from HTTPS to HTTP, I checked if everything is usable with HTTP by performing the requests via Postman.

Or is Python discarding HTTP responses that are not performed vie HTTPS but have an STS header?

![Screenshot from 2022-05-09 06-58-41](https://user-images.githubusercontent.com/15141351/167343827-474903af-5f50-4038-9aea-35ee9e3f1a90.png)

**Comment by GerdRuetten** [comment]
Yes, i'm sure :-)

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/97361636/167344997-bcad70ca-78d7-4c2e-a5df-59b58e17ad30.png">

**Comment by SpiGAndromeda** [comment]
@GerdRuetten working just fine in Firefox, Edge and Chrome is opening 
[http://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/10677/kml/MOSMIX_L_LATEST_10677.kmz](http://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/10677/kml/MOSMIX_L_LATEST_10677.kmz) 
and not 
[https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/10677/kml/MOSMIX_L_LATEST_10677.kmz](https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/10677/kml/MOSMIX_L_LATEST_10677.kmz).

And thats what the package does. There is also no 301 or 302 response redirecting to HTTPS

**Comment by cs42** [comment]
The certificate for opendata.dwd.de expired. They need to renew it.

**Comment by SpiGAndromeda** [comment]
I wrote DWD an email and got a reply. They are working on a "solution" (most likely getting a new certificate ... DFN certificates often take some days to be issued).

@FL550 do you have a working test environment and check if HSTS really is the problem and if allowing unsecure connections solve the problem? I still think going for HTTP instead of HTTPS is the way to go if it's working. (just to avoid future certificate problems).

**Comment by LuckyTriple7** [comment]
The certificate is now valid again. Problem solved with that.

**Comment by GerdRuetten** [comment]
> The certificate is now valid again. Problem solved with that.

Yes i confirm!

The DWD-side is use a new SSL-Cert.

But the new version from this packages use the non-secure http-URL.

Pls re-fix to the secure https-URL.

**Comment by FL550** [comment]
I've reverted the change, so the integration is using SSL again.
